### PR TITLE
list_new_xtals script. Lists GPCR xtals that are not yet in your version of GPCRdb

### PR DESCRIPTION
**Pull request by pszgaspar**
no new dependencies

### CODE REVIEW

**Comment by viis** [comment]
Please add dependencies in https://github.com/protwis/protwis_puppet_modules/blob/master/python/manifests/init.pp

**Comment by viis** [comment]
Why do you need both urllib3 AND requests?

**Comment by pszgaspar** [comment]
I used urllib for the pdb query and requests for parsing the html pages

2016-07-11 16:01 GMT+02:00 Vignir Isberg <notifications@github.com>:

**Comment by viis** [comment]
Couldn't you use requests for both? I ask because I want to minimize the number of dependencies. Besides, it doesn't seem like you are using urllib3, just urllib, which is built-in??

**Comment by pszgaspar** [comment]
yeah I know it's weird. i wrote the code on my laptop then tried it on
another machine and these were the packages it was complaining about. I
also don't get why it's urllib3. Don't accept the PR yet then, I'll try to
work around the urllib and make it work with requests only.

2016-07-11 16:23 GMT+02:00 Vignir Isberg <notifications@github.com>:

**Comment by pszgaspar** [comment]
I got rid of the dependencies. Now it runs using only urllib and re, which are built-in packages

**Pull request merged**
